In [35]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
#import category_encoders as ce
from sklearn.preprocessing import OrdinalEncoder

%matplotlib inline
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder
#from sklearn.model_selection import train_test_split
#from sklearn.model_selection import cross_val_score
#from sklearn.model_selection import KFold
#from sklearn.preprocessing import StandardScaler
#from sklearn.preprocessing import MinMaxScaler

#from sklearn.ensemble import GradientBoostingRegressor
#from sklearn.metrics import mean_squared_error

In [36]:
#Loading dataset
df = pd.read_csv('Downloads/Dataset/Train_data.csv')
dftest = pd.read_csv('Downloads/Dataset/Test_data.csv')
df.head()

Unnamed: 0 code clientType registrationMode planName  accident  duration  \
0           1  CBH      Basic          Offline        M         0       186   
1           2  CBH      Basic          Offline        M         0       186   
2           3  CWT      Basic           Online        Q         0        65   
3           4  CWT      Basic           Online        Q         0        60   
4           5  CWT      Basic           Online        Q         0        79   

     country  netSales  netProfit gender  age  
0   MALAYSIA     -29.0       9.57      F   81  
1   MALAYSIA     -29.0       9.57      F   71  
2  AUSTRALIA     -49.5      29.70    NaN   32  
3  AUSTRALIA     -39.6      23.76    NaN   32  
4      ITALY     -19.8      11.88    NaN   41

In [37]:
df.describe().T
#df.head()

count          mean           std    min       25%      50%  \
Unnamed: 0  60326.0  30163.500000  17414.760507    1.0  15082.25  30163.5   
accident    60326.0      0.014587      0.119895    0.0      0.00      0.0   
duration    60326.0     49.325233     99.493754   -2.0      9.00     22.0   
netSales    60326.0     40.762807     49.100660 -389.0     18.00     26.5   
netProfit   60326.0      9.839874     19.892750    0.0      0.00      0.0   
age         60326.0     39.987418     14.054040    0.0     35.00     36.0   

                 75%      max  
Unnamed: 0  45244.75  60326.0  
accident        0.00      1.0  
duration       53.00   4881.0  
netSales       48.00    810.0  
netProfit      11.55    283.5  
age            43.00    118.0

In [38]:
#dftest.describe().T
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60326 entries, 0 to 60325
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Unnamed: 0        60326 non-null  int64  
 1   code              60326 non-null  object 
 2   clientType        60326 non-null  object 
 3   registrationMode  60326 non-null  object 
 4   planName          60326 non-null  object 
 5   accident          60326 non-null  int64  
 6   duration          60326 non-null  int64  
 7   country           60326 non-null  object 
 8   netSales          60326 non-null  float64
 9   netProfit         60326 non-null  float64
 10  gender            17361 non-null  object 
 11  age               60326 non-null  int64  
dtypes: float64(2), int64(4), object(6)
memory usage: 5.5+ MB


In [39]:
df = df.drop(['Unnamed: 0'], axis =1)
df.head()

code clientType registrationMode planName  accident  duration    country  \
0  CBH      Basic          Offline        M         0       186   MALAYSIA   
1  CBH      Basic          Offline        M         0       186   MALAYSIA   
2  CWT      Basic           Online        Q         0        65  AUSTRALIA   
3  CWT      Basic           Online        Q         0        60  AUSTRALIA   
4  CWT      Basic           Online        Q         0        79      ITALY   

   netSales  netProfit gender  age  
0     -29.0       9.57      F   81  
1     -29.0       9.57      F   71  
2     -49.5      29.70    NaN   32  
3     -39.6      23.76    NaN   32  
4     -19.8      11.88    NaN   41

In [40]:
df['clientType'] = df['clientType'].replace({"Basic": 0})
df['clientType'] = df['clientType'].replace({"Premium": 1})
df['registrationMode'] = df['registrationMode'].replace({"Offline": 0})
df['registrationMode'] = df['registrationMode'].replace({"Online": 1})
df.head()

code  clientType  registrationMode planName  accident  duration    country  \
0  CBH           0                 0        M         0       186   MALAYSIA   
1  CBH           0                 0        M         0       186   MALAYSIA   
2  CWT           0                 1        Q         0        65  AUSTRALIA   
3  CWT           0                 1        Q         0        60  AUSTRALIA   
4  CWT           0                 1        Q         0        79      ITALY   

   netSales  netProfit gender  age  
0     -29.0       9.57      F   81  
1     -29.0       9.57      F   71  
2     -49.5      29.70    NaN   32  
3     -39.6      23.76    NaN   32  
4     -19.8      11.88    NaN   41

In [41]:
df.code.convert_dtypes(convert_string=True)

0        CBH
1        CBH
2        CWT
3        CWT
4        CWT
        ... 
60321    JZI
60322    JZI
60323    JZI
60324    JZI
60325    JZI
Name: code, Length: 60326, dtype: string

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60326 entries, 0 to 60325
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   code              60326 non-null  object 
 1   clientType        60326 non-null  int64  
 2   registrationMode  60326 non-null  int64  
 3   planName          60326 non-null  object 
 4   accident          60326 non-null  int64  
 5   duration          60326 non-null  int64  
 6   country           60326 non-null  object 
 7   netSales          60326 non-null  float64
 8   netProfit         60326 non-null  float64
 9   gender            17361 non-null  object 
 10  age               60326 non-null  int64  
dtypes: float64(2), int64(5), object(4)
memory usage: 5.1+ MB


In [43]:
dataset = df.values
X = dataset[:,1:10]
Y = dataset[:,10]
X,Y

(array([[0, 0, 'M', ..., -29.0, 9.57, 'F'],
        [0, 0, 'M', ..., -29.0, 9.57, 'F'],
        [0, 1, 'Q', ..., -49.5, 29.7, nan],
        ...,
        [1, 1, 'I', ..., 18.0, 6.3, 'M'],
        [1, 1, 'I', ..., 18.0, 6.3, 'M'],
        [1, 1, 'I', ..., 26.0, 9.1, 'F']], dtype=object),
 array([81, 71, 32, ..., 57, 63, 35], dtype=object))

In [44]:
df[['code', 'planName', 'country','gender']] = df[['code', 'planName', 'country','gender']].astype("|S" )
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60326 entries, 0 to 60325
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   code              60326 non-null  object 
 1   clientType        60326 non-null  int64  
 2   registrationMode  60326 non-null  int64  
 3   planName          60326 non-null  object 
 4   accident          60326 non-null  int64  
 5   duration          60326 non-null  int64  
 6   country           60326 non-null  object 
 7   netSales          60326 non-null  float64
 8   netProfit         60326 non-null  float64
 9   gender            60326 non-null  object 
 10  age               60326 non-null  int64  
dtypes: float64(2), int64(5), object(4)
memory usage: 5.1+ MB


In [26]:
df.replace(to_replace = np.nan, value =0, inplace=True)

In [27]:
df.head()

code  clientType  registrationMode planName  accident  duration  \
0  b'CBH'           0                 0     b'M'         0       186   
1  b'CBH'           0                 0     b'M'         0       186   
2  b'CWT'           0                 1     b'Q'         0        65   
3  b'CWT'           0                 1     b'Q'         0        60   
4  b'CWT'           0                 1     b'Q'         0        79   

        country  netSales  netProfit  gender  age  
0   b'MALAYSIA'     -29.0       9.57    b'F'   81  
1   b'MALAYSIA'     -29.0       9.57    b'F'   71  
2  b'AUSTRALIA'     -49.5      29.70  b'nan'   32  
3  b'AUSTRALIA'     -39.6      23.76  b'nan'   32  
4      b'ITALY'     -19.8      11.88  b'nan'   41

In [54]:
encoder = OrdinalEncoder()
# transform data
result = encoder.fit_transform(df)
print(result)

[[  3.   0.   0. ... 392.   0.  80.]
 [  3.   0.   0. ... 392.   0.  70.]
 [  6.   0.   1. ... 707.   2.  31.]
 ...
 [  9.   1.   1. ... 305.   1.  56.]
 [  9.   1.   1. ... 305.   1.  62.]
 [  9.   1.   1. ... 383.   0.  34.]]


In [49]:
#X_train, X_test, Y_train, Y_test = train_test_split (X, Y, test_size = 0.20, random_state=
#print(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)